### ISSUE TITLE
Zero memory on drop

### ISSUE THREAD

**Issue by bjorn3** [49nord/sec-rs#3]

**Comment by mbr** [comment]
This is probably not feasible, especially if the type `T` is heap allocated, which would rule out all strings. Zeroing should probably done through a different crate and properly through traits. Probably one named `TopSecret` =).

**Comment by mbr** [comment]
With that being said, I will be closing this. Let me know if you think I am wrong.

**Comment by bjorn3** [comment]
No problem.
